#!/usr/bin/env python
import os
import sys
from os.path import dirname, join
import time
import subprocess

#################### Common Parameters ####################
mpi_cmd = "OMP_NUM_THREADS=12 yhrun -p nsfc2 --ntasks-per-node=2 --cpu_bind=rank_ldom -n 1 "
#mpi_cmd = "OMP_NUM_THREADS=%s yhrun -p nsfc2 --cpu_bind=rank_ldom -N 1 " % sys.argv[1]
hosts = ""

#################### LDA Parameters ####################
exe_file = "./src/model/hlda/hlda" 
#params = {
#'prefix': "../data/nysmaller/nysmaller",
#'beta': "1,0.5,0.25,0.1",
##'beta': "0.5,0.25,0.125,0.06",
#'log_gamma': "-17",
#'alpha': "0.2",
#'L': "4",
#'topic_limit': "1000",
#'init_iiter': "10",
#'n_mc_iters': "30",
#'n_iters': "70",
#'threshold': 0#50000
#}
#params = {
#'prefix': "../data/nytimes_new/nytimes",
#'beta': "1,0.5,0.25,0.125",
#'log_gamma': "-40",
#'threshold': 128,
#'L': "4",
#'topic_limit': "1000"
#}
params = {
'prefix': "../data/nytimes",
'beta': "1,0.5,0.25,0.125",
'log_gamma': "-40",
'alpha': "0.2",
'L': "4",
'topic_limit': "1000",
'init_iiter': "10",
'n_mc_iters': "30",
'n_iters': "70",
'threshold': 128,
}
#params = {
#'prefix': "../data/pubmed",
#'beta': "1,0.5,0.25,0.125,0.0625",
#'gamma': "1e-50",
#'threshold': 128,
#'L': "5",
#'alpha': "100,80,64,50,40", #TODO random start
#'topic_limit': "1000"
#}
#params = {
#'prefix': "../data/clueweb_s5/clueweb",
#'beta': "9.6,3.84,1.5,0.6,0.24",
##'beta': "6.4,2.56,1.0,0.4,0.16",
##'beta': "3.2,1.28,0.5,0.2,0.08",
##'beta': "2.4,1.0,0.4,0.16,0.064",
##'beta': "6.4,3.2,1.6,0.8,0.4",
##'beta': "6.4,2.3,0.85,0.31,0.11",
##'beta': "12.8,5.12,2.0,0.8,0.32",
#'log_gamma': "-900,-700,-500,-300",
##'log_gamma': "-1350,-1050,-750,-450",
##'log_gamma': "-1440,-1120,-800,-480",
#'threshold': 1024,
#'L': "5",
#'alpha': "100,80,64,50,40",
#'topic_limit': "1000",
#'init_iiter': "10",
#'n_mc_iters': "50",
#'n_iters': "100"
#}
#params = {
#'prefix': "../data/clueweb_moderate/clueweb",
#'beta': "3.2,1.6,0.8,0.4,0.2",
#'log_gamma': '-9600,-7800,-6000,-4200',
#'threshold': 4096,
#'L': "5",
#'alpha': "50,40,32,25,20",
#'topic_limit': "1000"
#}
lda = mpi_cmd + hosts + exe_file
for p, v in params.iteritems():
    lda += " --%s=%s" % (p, str(v))

####################    Execute     ####################
cmd = lda
print cmd
os.system(cmd)
