#!/usr/bin/env python
import os
import sys
from os.path import dirname, join
import time
import subprocess

#################### Common Parameters ####################
mpi_cmd = "OMP_NUM_THREADS=12 "
hosts = ""

#################### LDA Parameters ####################
exe_file = "./src/model/hlda/hlda" 
params = {
'prefix': "../data/nysmaller/nysmaller",
'beta': "1,0.5,0.25,0.1",
'log_gamma': "-17",
'alpha': "0.2",
'L': "4",
'topic_limit': "1000",
'init_iiter': "10",
'n_mc_iters': "30",
'n_iters': "70",
'threshold': 0
}
lda = mpi_cmd + hosts + exe_file
for p, v in params.iteritems():
    lda += " --%s=%s" % (p, str(v))

####################    Execute     ####################
cmd = lda
print cmd
os.system(cmd)
