#!/usr/bin/env python
import os
import sys
from os.path import dirname, join
import time
import subprocess

#################### Common Parameters ####################
mpi_cmd = "OMP_NUM_THREADS=12 numactl -N 1 "
hosts = ""

#################### LDA Parameters ####################
exe_file = "./src/model/hlda/hlda" 
params = {
'prefix': "../data/nytimes/nytimes",
'beta': "1,0.5,0.25,0.125",
'log_gamma': "-40",
#'alpha': "0.2",
'threshold': 1000000,
#'init_iiter': "10",
'n_mc_iters': "30",
'n_iters': "70",
'L': "4",
'topic_limit': "1000"
}
lda = mpi_cmd + hosts + exe_file
for p, v in params.iteritems():
    lda += " --%s=%s" % (p, str(v))

####################    Execute     ####################
cmd = lda
print cmd
os.system(cmd)
